---
- name: Create User - "{{ backup_username }}"
  win_domain_user:
    name: "{{ backup_username }}"
    #firstname: "{{ backup_user }}"   
    #surname: administrator
    #company: layer0.xyz
    password: "{{ backup_user_password }}"
    state: present
    groups:
      - Domain Admins
      - Domain Users
    country: US
    domain_username: "{{domain_admin_user}}"
    domain_password: "{{domain_admin_password}}"
    domain_server: "{{DC_address}}"
